### ISSUE TITLE
Date format validation

### ISSUE THREAD

**Issue by lytex** [lyz-code/pydo#57]
I added a due date with the wrong format
`pydo add Test due:2020-04-20 18:10`
pydo adds the wrong date without any error or warning, but then fails when listing all tasks.
It would be better to detect the error before adding the task to the database.
Traceback:
```
Traceback (most recent call last):
  File "/home/julian/.virtualenvs/pydo/bin/pydo", line 11, in <module>
    load_entry_point('pydo', 'console_scripts', 'pydo')()
  File "/home/julian/code/python/pydo/pydo/__init__.py", line 59, in main
    List(session).print(
  File "/home/julian/code/python/pydo/pydo/reports.py", line 135, in print
    task_report.append(self._date2str(task.due))
  File "/home/julian/code/python/pydo/pydo/reports.py", line 47, in _date2str
    return date.strftime(self.config.get('report.date_format'))
  File "/home/julian/code/python/pydo/pydo/manager.py", line 697, in get
    config = self._get(id)
  File "/home/julian/code/python/pydo/pydo/manager.py", line 158, in _get
    raise ValueError('The element {} does not exist'.format(id))
ValueError: The element report.date_format does not exist
```

**Comment by lytex** [comment]
It seems I was using a old version and/or old database scheme
